services:
  db:
    image: postgres
    container_name: coupon-postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=coupon_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coupon-web
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - db

volumes:
 pgdata: